LANGUAGE=cs

DATA_NAME=pdt

TRAIN_DATA=${CZENG_COREF_DIR}/data/cs/analysed/pdt/train/0004/list
DEV_DATA=${CZENG_COREF_DIR}/data/cs/analysed/pdt/dev/0004/list
EVAL_DATA=${CZENG_COREF_DIR}/data/cs/analysed/pdt/eval/0004/list

TRAIN_BASELINE_DATA=${CZENG_COREF_DIR}/data/cs/analysed/pdt/train/0003/list
DEV_BASELINE_DATA=${CZENG_COREF_DIR}/data/cs/analysed/pdt/dev/0003/list
EVAL_BASELINE_DATA=${CZENG_COREF_DIR}/data/cs/analysed/pdt/eval/0003/list
