include ../makefile.lang
include ../../makefile.main

ANAPH_TYPE=all_anaph
COREF_MODULES="relpron,reflpron,perspron"

#BASELINE_SCEN=A2T::CS::MarkRelClauseCoref A2T::CS::MarkReflpronCoref A2T::SetDocOrds A2T::CS::MarkTextPronCoref Coref::RearrangeLinks retain_cataphora=1
