include ../makefile.lang
include ../../makefile.main

ANAPH_TYPE=reflpron
MAIN_COREF_BLOCK=Coref::CS::ReflPron::Resolve diagnostics=1
COREF_MODULES="relpron"

#BASELINE_SCEN=A2T::CS::MarkRelClauseCoref A2T::CS::MarkReflpronCoref
